# -*- coding: utf-8 -*-
"""бот вавилон

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-hpJ9DdsCoA4NL1qJIPV72SoXRJhrFe
"""

import os
import logging
import requests
from io import BytesIO  # Добавьте этот импорт
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup, InputMediaPhoto
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    filters,
    CallbackContext,
    CallbackQueryHandler,
    ConversationHandler,
)

# Настройка логирования
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# Состояния для ConversationHandler
DATE, PHONE, PARENT_NAME, GIRL_NAME, AGE, EXPERIENCE, SOURCE = range(7)

# База данных
user_data_db = {}

# Загрузка переменных окружения
TOKEN = os.getenv('TELEGRAM_TOKEN')
ADMIN_CHAT_ID = os.getenv('ADMIN_CHAT_ID')

# GitHub репозиторий
GITHUB_REPO_URL = "https://raw.githubusercontent.com/syakimmm/vavilon/main/"

# Меню бота
async def start(update: Update, context: CallbackContext) -> None:
    keyboard = [
        [InlineKeyboardButton("📝 Записаться", callback_data="signup")],
        [InlineKeyboardButton("ℹ️ О нас", callback_data="about")],
        [InlineKeyboardButton("🎒 Что взять", callback_data="requirements")],
        [InlineKeyboardButton("🆘 Помощь", callback_data="help")],
        [
            InlineKeyboardButton("📅 Программа", callback_data="program"),
            InlineKeyboardButton("📍 Адрес", callback_data="location")
        ],
        [InlineKeyboardButton("📞 Контакты", callback_data="contacts")]
    ]

    if update.message:
        await update.message.reply_text(
            "Привет! Я бот для записи на занятия. 🩰\nВыберите действие:",
            reply_markup=InlineKeyboardMarkup(keyboard)
        )
    else:
        query = update.callback_query
        await query.answer()
        await query.edit_message_text(
            "Главное меню:",
            reply_markup=InlineKeyboardMarkup(keyboard)
        )

# Обработчики для всех кнопок
async def button_handler(update: Update, context: CallbackContext) -> None:
    query = update.callback_query
    await query.answer()

    handlers = {
        'about': about_handler,
        'requirements': requirements_handler,
        'program': program_handler,
        'location': location_handler,
        'contacts': contacts_handler,
        'help': help_handler,
        'signup': signup_handler,
        'back_to_menu': back_to_menu_handler
    }

    handler = handlers.get(query.data)
    if handler:
        await handler(update, context)

async def about_handler(update: Update, context: CallbackContext) -> None:
    query = update.callback_query
    try:
        await send_github_photo(
            update,
            context,
            "166979-chelovek_pauk_net_dorogi_domoj-chelovek_pauk-kinovselennaya_marvel-studiya_marvel-mir-3840x2160.jpg",
            "🌟 О нашей студии:\nПрофессиональные педагоги с 10-летним опытом"
        )
    except Exception as e:
        await query.edit_message_text(f"⚠️ Ошибка: {str(e)}")
    finally:
        await show_back_button(update, context)

async def requirements_handler(update: Update, context: CallbackContext) -> None:
    query = update.callback_query
    try:
        await send_github_photo(
            update,
            context,
            "166979-chelovek_pauk_net_dorogi_domoj-chelovek_pauk-kinovselennaya_marvel-studiya_marvel-mir-3840x2160.jpg",
            "🎒 Что взять с собой:\n• Форму для танцев\n• Чешки/балетки\n• Бутылку воды"
        )
    except Exception as e:
        await query.edit_message_text(f"⚠️ Ошибка: {str(e)}")
    finally:
        await show_back_button(update, context)

async def program_handler(update: Update, context: CallbackContext) -> None:
    query = update.callback_query
    await query.edit_message_text(
        "📅 Программа занятий:\n\n1. Разминка (15 мин)\n2. Основная часть (40 мин)\n3. Растяжка (15 мин)",
        reply_markup=back_to_menu_keyboard()
    )

async def location_handler(update: Update, context: CallbackContext) -> None:
    query = update.callback_query
    await context.bot.send_location(
        chat_id=query.message.chat_id,
        latitude=56.468238,
        longitude=84.948214
    )
    await query.edit_message_text(
        "📍 Наш адрес:\nг. Томск, ул. Иркутский тракт, 86/1\nДом культуры «Маяк»",
        reply_markup=back_to_menu_keyboard()
    )

async def contacts_handler(update: Update, context: CallbackContext) -> None:
    query = update.callback_query
    await query.edit_message_text(
        "📞 Наши контакты:\n\nТелефон: +7 (913) 880-84-58\nEmail: info@studio.ru",
        reply_markup=back_to_menu_keyboard()
    )

async def help_handler(update: Update, context: CallbackContext) -> None:
    query = update.callback_query
    await query.edit_message_text(
        "🆘 Помощь:\n\nЕсли бот не отвечает:\n1. Проверьте соединение\n2. Попробуйте позже\n3. Напишите нам",
        reply_markup=back_to_menu_keyboard()
    )

async def signup_handler(update: Update, context: CallbackContext) -> None:
    query = update.callback_query
    await query.edit_message_text(
        "📝 Запись на занятие:\n\nВыберите дату:",
        reply_markup=InlineKeyboardMarkup([
            [InlineKeyboardButton("Понедельник", callback_data="date_mon")],
            [InlineKeyboardButton("Среда", callback_data="date_wed")],
            [InlineKeyboardButton("Пятница", callback_data="date_fri")],
            [InlineKeyboardButton("◀️ Назад", callback_data="back_to_menu")]
        ])
    )

async def back_to_menu_handler(update: Update, context: CallbackContext) -> None:
    await start(update, context)

# Вспомогательные функции
async def send_github_photo(update: Update, context: CallbackContext, filename: str, caption: str = ""):
    """Отправка фото из GitHub"""
    photo_url = f"{GITHUB_REPO_URL}{filename}"
    try:
        response = requests.get(photo_url, timeout=10)
        response.raise_for_status()
        await context.bot.send_photo(
            chat_id=update.effective_chat.id,
            photo=BytesIO(response.content),
            caption=caption
        )
    except Exception as e:
        logger.error(f"Ошибка отправки фото: {e}")
        raise

async def show_back_button(update: Update, context: CallbackContext):
    """Показывает кнопку возврата"""
    await context.bot.send_message(
        chat_id=update.effective_chat.id,
        text="Выберите действие:",
        reply_markup=back_to_menu_keyboard()
    )

def back_to_menu_keyboard():
    """Клавиатура для возврата в меню"""
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("◀️ В меню", callback_data="back_to_menu")]
    ])

def main() -> None:
    application = Application.builder().token(TOKEN).build()

    # Регистрация обработчиков
    application.add_handler(CommandHandler('start', start))
    application.add_handler(CallbackQueryHandler(button_handler))

    application.run_polling()

if __name__ == '__main__':
    main()